package com.mentos_koder.remote_lg_tv.util

enum class KeycodeLG(val value: String) {
    LEFT("LEFT"),
    RIGHT("RIGHT"),
    DOWN("DOWN"),
    UP("UP"),
    HOME("HOME"),
    BACK("BACK"),
    ENTER("ENTER"),
    DASH("DASH"),
    INFO("INFO"),
    ASTERISK("ASTERISK"),
    CC("CC"),
    EXIT("EXIT"),
    MUTE("MUTE"),
    RED("RED"),
    GREEN("GREEN"),
    BLUE("BLUE"),
    YELLOW("YELLOW"),
    VOLUMEUP("VOLUMEUP"),
    VOLUMEDOWN("VOLUMEDOWN"),
    CHANNELUP("CHANNELUP"),
    CHANNELDOWN("CHANNELDOWN"),
    MENU("MENU"),
    SEARCH("SEARCH"),
    SETTING("SETTING"),
    GUIDE("GUIDE"),
    LIST("LIST"),
    HDMI("HDMI"),
    SOURCE("SOURCE"),
    PLAY("PLAY"),
    PAUSE("PAUSE"),
    ZERO("0"),
    ONE("1"),
    TWO("2"),
    THREE("3"),
    FOUR("4"),
    FIVE("5"),
    SIX("6"),
    SEVEN("7"),
    EIGHT("8"),
    NINE("9"),
    REPEAT("REPEAT"),
    SEARCHVOICE("com.webos.app.voice"),
    TV_INPUT("com.webos.app.livetv"),
    HDMI1("HDMI1"),
    HDMI2("HDMI2"),
    HDMI3("HDMI3"),
    HDMI4("HDMI4"),
    AV_MODE("AV"), // AV_1
    COMPONENT1("SCART"), // SCART_1
    RECORD("REC"),
    POWER("POWER"),
    INPUT("INPUT")
}
